// Dev-only: regenerate the loading wordmark. Never imported at runtime.
// Usage: npm run gen:ascii -- [TEXT] [OUT_PATH] [FONT]
import figlet from "figlet";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const text = process.argv[2] ?? "YAUMICUARIO";
const out = process.argv[3] ?? "src/assets/ascii/yaumicuario.ts";
const font = process.argv[4] ?? "ANSI Shadow";
const art = figlet.textSync(text, { font });

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/generate-ascii.mjs; do not edit by hand.\n` +
    `export const yaumicuarioArt = ${JSON.stringify(art)};\n`,
);

console.log(art);
console.log(`\nWrote ${out}`);
